name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # we need this to map platform names as used by github to
        # the attribute names defined in release.nix
        include:
          - os: ubuntu-latest
            os_attr_name: linux
          - os: macos-latest
            os_attr_name: darwin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: cachix/install-nix-action@v10
      with:
        # we use the nixpkgs defined in default.nix
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: dapp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build release.nix -A dapphub.${{ matrix.os_attr_name }}.stable
