name: "Release"
on:
  push:
    tags:
      - '[a-z]+/[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # v12
      - uses: cachix/install-nix-action@v12
      # v8
      - uses: cachix/cachix-action@v8
        with:
          name: dapp
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build -A hevmUnwrapped --out-link hevm

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: hevm-linux
          path: ./hevm/bin/hevm

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
